@startuml
'https://plantuml.com/state-diagram

[*] --> Экран_Задач

state Экран_Задач {
  [*] --> Сделать
  [*] --> Делаю
  [*] ---> Добавить_задачу
  [*] --> Сделано
  Добавить_задачу --> Экран_создания_задачи
  state Сделать{
    [*] --> Список_задач
  }
  state Делаю{
  [*] --> Список_задач
  }
  state Сделано{
  [*] --> Список_задач
  }
  state Список_задач{
  [*] --> Задача
  Задача --> Действия
  }
  state Действия{
  [*] --> Начать
  [*] --> Завершить
  [*] --> Изменить
  Изменить --> Экран_изменения_задачи
  [*] --> Удалить
  }
}

state Экран_создания_задачи {
    [*] --> Назад
    Назад --> Экран_Задач
    [*] --> Создать
    Создать --> Экран_Задач
    [*] --> Ввод_названия
    [*] --> Ввод_описания
    [*] --> Ввод_дедлайна
}
state Экран_изменения_задачи{
    [*] --> Назад_
    Назад_ --> Экран_Задач
    [*] --> Изменить_
    Изменить_ --> Экран_Задач
    [*] --> Изменение_названия
    [*] --> Изменение_описания
    [*] --> Изменение_дедлайна
}

@enduml