@startuml
'https://plantuml.com/sequence-diagram

autonumber

CatalogScene -> TaskScene: Переход на страницу
TaskScene ->TaskCubit: Функция редакции задачи
TaskCubit -> AppDatabase: Запрос обновления задачи
AppDatabase -> CatalogCubit: Список задач
CatalogCubit -> CatalogScene: Список задач
@enduml