@startuml
'https://plantuml.com/component-diagram


package "Пользовательское приложение" {
    [Пользовательский интерфейс]
    [Логическая прослойка]
    [Данные и запросы]
}

database "База данных SqlLite" {
    [Обработчик запросов]
  folder "Таблица записей" {
    [Номер]
    [Заголовк]
    [Описание]
    [Дедлайн]
    [Состояние]
  }
}

[Пользовательский интерфейс] <--> [Логическая прослойка]
[Логическая прослойка]<-->[Данные и запросы]
[Данные и запросы]<-->[Обработчик запросов]

@enduml