@startuml
'https://plantuml.com/deployment-diagram

actor Пользователь

agent Клиентское_приложение


database База_данных


Пользователь --> Клиентское_приложение
Клиентское_приложение <--> База_данных

@enduml